spring.application.name=finance-backend
# ============================================
# DATABASE CONFIGURATION
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=manas@16
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA/HIBERNATE CONFIGURATION
# ============================================
# Create/update tables automatically
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries
spring.jpa.show-sql=true
# Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# SERVER CONFIGURATION
# ============================================
# Port
server.port=8080
# API prefix
server.servlet.context-path=/api/v1

# ============================================
# LOGGING
# ============================================
logging.level.root=INFO
logging.level.com.zorvvyn=DEBUG
logging.level.org.springframework.web=DEBUG